services:
  - type: web
    name: bnv-user-management-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
